config/routes.rb
Rails.application.routes.draw do
  resources :matches 
  resources :players
  resources :teams
  resources :events
  resources :championships
  devise_for :users, controllers:{
  	 omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"


  authenticated :user do
  	root 'main#home'
  end




  unauthenticated :user do
  	root 'main#unregistered'
  end

  
  get  'matches-create' => 'matches#generate_form'
  post 'matches-generate' => 'matches#generate'
  
  get  'details_match/:match_id/new'    => 'details_matches#new_detail'
  post 'details_match/:match_id/create' => 'details_matches#create_detail'
  get  'matches/:match_id/close' => 'matches#close'
  get  'search-players' => 'players#search'
  get  'staticstics/table-positions' => 'staticstics#table_positions'
  get  'staticstics/table-events' => 'staticstics#table_players_goals'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/championship.rb
class Championship < ApplicationRecord
	has_many :matches
	has_many :championships
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :set_championship, only: [:show, :edit, :update, :destroy]

  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
  end

  # GET /championships/new
  def new
    @championship = Championship.new
  end

  # GET /championships/1/edit
  def edit
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to '/championships', notice: 'Championship was successfully created.' }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1
  # PATCH/PUT /championships/1.json
  def update
    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: 'Championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def championship_params
      params.require(:championship).permit(:name, :quantity_min_teams, :date_initial_inscription, :date_end_inscription, :match_duration, :matches_simultanius, :game_days)
    end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.haml
= form_for @championship do |f|
  %h2 New championship
  - if @championship.errors.any?
    #error_explanation
      %h3= "#{pluralize(@championship.errors.count, "error")} prohibited this championship from being saved:"
      %ul
        - @championship.errors.full_messages.each do |msg|
          %li= msg
  .form-group.row 
    = f.label :name,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :name,class:"form-control"
  .form-group.row
    = f.label :quantity_min_teams,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.number_field :quantity_min_teams,class:"form-control"
  .form-group.row
    = f.label :date_initial_inscription,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :date_initial_inscription,class:"form-control"
  .form-group.row
    = f.label :date_end_inscription,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :date_end_inscription,class:"form-control"
  .form-group.row
    = f.label :match_duration,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :match_duration,class:"form-control"
  .form-group.row
    = f.label :matches_simultanius,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :matches_simultanius,class:"form-control"
  .form-group.row
    = f.label :game_days,class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :game_days,class:"form-control"
  .form-group.row
    .offset-md-2.col-md-4
      %button.btn.btn-success{"type"=>"submit"}
        %i.fa.fa-floppy-o{"aria-hidden"=>"true"}
        %span  Save team
  .form-group.row
    .offset-md-2.col-md-4
      %a.btn.btn-secondary.active{"href"=>"/championships"} <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back 

app/views/championships/edit.html.haml
.col-xs-20.col-sm-10.col-md-8.col-lg-6 
  .box       
    .big-padding
      %h1 Editing championship
      = render 'form'
      = link_to 'Show', @championship
      = link_to 'Back', championships_path

app/views/championships/index.html.haml
.col-xs-12.col-sm-12.col-md-12.col-lg-12{"style"=>"background: white;"}
  .big-padding
    .big-padding{"style"=>"border:solid #f7f7f9;"}
      %h1 Championships
      %table.table.table-striped
        %thead
          %tr
            %th #
            %th Name
            %th.hidden-sm-down Quantity min teams
            %th.hidden-sm-down Date initial inscription
            %th.hidden-sm-down Date end inscription
            %th
        %tbody
          - @championships.each do |championship|
            %tr
              %td= championship.id
              %td= championship.name
              %td.hidden-sm-down= championship.quantity_min_teams
              %td.hidden-sm-down= championship.date_initial_inscription
              %td.hidden-sm-down= championship.date_end_inscription
              %td
                .dropdown
                  %button.btn.btn-secondary.dropdown-toggle{"type"=>"button","id"=>"actions","data-toggle"=>"dropdown","aria-haspopup"=>"true","aria-expanded"=>"false"} Actions
                  .dropdown-menu{"aria-labelledby"=>"actions"}
                    = link_to 'Show', championship,:class=>"dropdown-item"
                    = link_to 'Edit', edit_championship_path(championship),:class=>"dropdown-item"
                    %a.dropdown-item{"href"=>"/teams?championship_id=#{championship.id}"} Teams
                    %a.dropdown-item{"href"=>"/matches?championship_id=#{championship.id}"} Matches
                    %a.dropdown-item{"href"=>"/matches-create?championship_id=#{championship.id}"} Programation
                    = link_to 'Destroy', championship, :method => :delete, :class=>"dropdown-item",:data => { :confirm => 'Are you sure?' }
      %br
      %a.btn.btn-success{"href"=>"/championships/new"} <i class="fa fa-plus" aria-hidden="true"></i> Add

app/views/championships/new.html.haml
.col-xs-12.col-md-9.col-md-offset-3
  .box       
    .big-padding
      = render 'form'
      

app/views/championships/show.html.haml
.col-xs-18.col-sm-8.col-md-6.col-lg-4 
  .box       
    .big-padding
      %p#notice= notice
      %table.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp
        %thead
          %tr
            %th.text-center{:colspan => 2,style:"text-align:center;"}= @championship.name
        %tbody
          %tr
            %td quantity_min_teams:
            %td= @championship.quantity_min_teams
          %tr
            %td date_initial_inscription:
            %td= @championship.date_initial_inscription
          %tr
            %td date_end_inscription:
            %td= @championship.date_end_inscription
          %tr
            %td match_duration:
            %td= @championship.match_duration
          %tr
            %td matches_simultanius:
            %td= @championship.matches_simultanius
          %tr
            %td game_days:
            %td= @championship.game_days

      %br
      = link_to 'Edit', edit_championship_path(@championship)
      = link_to 'Back', championships_path