config/routes.rb
Rails.application.routes.draw do
  resources :matches 
  resources :players
  resources :teams
  resources :events
  resources :championships
  devise_for :users, controllers:{
  	 omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"


  authenticated :user do
  	root 'main#home'
  end




  unauthenticated :user do
  	root 'main#unregistered'
  end

  
  get  'matches-create' => 'matches#generate_form'
  post 'matches-generate' => 'matches#generate'
  
  get  'details_match/:match_id/new'    => 'details_matches#new_detail'
  post 'details_match/:match_id/create' => 'details_matches#create_detail'
  get  'matches/:match_id/close' => 'matches#close'
  get  'search-players' => 'players#search'
  get  'staticstics/table-positions' => 'staticstics#table_positions'
  get  'staticstics/table-events' => 'staticstics#table_players_goals'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :details_matches
  has_attached_file :foto,styles: {thumb:"60x60",medium:"100x100"},default_url:"/images/players/:style_missing.png",url: "/images/players/:id/:style_:filename",:path => ":rails_root/public/images/players/:id/:style_:filename"
  validates_attachment_content_type :foto, content_type:/\Aimage\/.*\z/
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    team_id=params[:team_id]
    @players = Player.where(team_id: team_id)
    @players = Player.all if @players.blank? && !params[:team_id].present?

  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @teams = Team.all
  end

  # GET /players/1/edit
  def edit
  end

  def search 
    @players = Player.order(:first_name,:last_name).where("(first_name like ? or id = ? or tshirt_number = ? or last_name like ?) and team_id=? and status=0","%#{params[:term]}%",params[:term],params[:term],"%#{params[:term]}%",params[:team_id])
    render json: @players
  end


  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to '/players?team_id=' << @player.team_id.to_s, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :telefono, :email, :movil, :number_id, :team_id,:term,:tshirt_number,:foto)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player,:html => { :multipart => true } do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .form-group.row
    = f.label :first_name,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :first_name,class:"form-control"
  .form-group.row
    = f.label :last_name,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :last_name,class:"form-control"
  .form-group.row
    = f.label :telefono,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :telefono,class:"form-control"
  .form-group.row
    = f.label :email,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :email,class:"form-control"
  .form-group.row
    = f.label :movil,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :movil,class:"form-control"
  .form-group.row
    = f.label :number_id,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :number_id,class:"form-control"
  .form-group.row
    = f.label :team,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.collection_select(:team_id, @teams, :id, :name, {:prompt=>true}, {:class=>'form-control'})
  .form-group.row
    = f.label :tshirt_number,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :tshirt_number,class:"form-control"
  .form-group.row
    = f.label :foto,class:"col-sm-4 col-md-3 col-xs-12 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.file_field :foto,class:"form-control"

  .form-group.row
    .offset-md-3.col-md-4
      %button.btn.btn-success{"type"=>"submit"}
        %i.fa.fa-floppy-o{"aria-hidden"=>"true"}
        %span  Save player

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
.col-xs-12.col-sm-12.col-md-12.col-lg-12{"style"=>"background: white;"}
  .big-padding
    .big-padding{"style"=>"border:solid #f7f7f9;"}
      %h1 Players
      %table.table.table-striped 
        %thead
          %tr
            %th #
            %th 
            %th Names
            %th.hidden-sm-down Telefono
            %th.hidden-sm-down Email
            %th.hidden-sm-down Movil
            %th.hidden-sm-down Number
            %th.hidden-sm-down Team
            %th

        %tbody
          - @players.each do |player|
            %tr
              %td= player.id
              %td
                .avatar-team{style:"background-image:url(#{player.foto.url(:thumb)});"}
              %td
                = player.first_name
                = player.last_name
              %td.hidden-sm-down= player.telefono
              %td.hidden-sm-down= player.email
              %td.hidden-sm-down= player.movil
              %td.hidden-sm-down= player.number_id
              %td.hidden-sm-down= player.team.name
              %td
                .dropdown
                  %button.btn.btn-secondary.dropdown-toggle{"type"=>"button","id"=>"actions","data-toggle"=>"dropdown","aria-haspopup"=>"true","aria-expanded"=>"false"} Actions
                  .dropdown-menu{"aria-labelledby"=>"actions"}
                    = link_to 'Show', player,:class=>"dropdown-item"
                    = link_to 'Edit', edit_player_path(player),:class=>"dropdown-item"
                    = link_to 'Destroy', player, :method => :delete, :class=>"dropdown-item",:data => { :confirm => 'Are you sure?' }
      %br

      %a.btn.btn-success{"href"=>"/players/new"} <i class="fa fa-plus" aria-hidden="true"></i> Add

app/views/players/new.html.haml
.col-xs-12.col-sm-12.col-md-12.col-lg-12 
  .box       
    .big-padding
      %h1 New player
      = render 'form'
      %a.btn.btn-secondary.active{"href"=>"/players"} <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back 

app/views/players/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @player.first_name
%p
  %b Last name:
  = @player.last_name
%p
  %b Telefono:
  = @player.telefono
%p
  %b Email:
  = @player.email
%p
  %b Movil:
  = @player.movil
%p
  %b Number:
  = @player.number_id
%p
  %b Team:
  = @player.team.name

= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path