config/routes.rb
Rails.application.routes.draw do
  resources :matches 
  resources :players
  resources :teams
  resources :events
  resources :championships
  devise_for :users, controllers:{
  	 omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"


  authenticated :user do
  	root 'main#home'
  end




  unauthenticated :user do
  	root 'main#unregistered'
  end

  
  get  'matches-create' => 'matches#generate_form'
  post 'matches-generate' => 'matches#generate'
  
  get  'details_match/:match_id/new'    => 'details_matches#new_detail'
  post 'details_match/:match_id/create' => 'details_matches#create_detail'
  get  'matches/:match_id/close' => 'matches#close'
  get  'search-players' => 'players#search'
  get  'staticstics/table-positions' => 'staticstics#table_positions'
  get  'staticstics/table-events' => 'staticstics#table_players_goals'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :local, :class_name => "Team",:foreign_key  => "local_id" 
  belongs_to :visitant, :class_name => "Team",:foreign_key  => "visitant_id" 
  belongs_to :championship
  has_many :details_matches
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy, :details_form]

  # GET /matches
  # GET /matches.json
  def index
    championship_id=params[:championship_id]
    @matches = Match.where(championship_id: championship_id)
    @matches = Match.all if @matches.blank? && !params[:championship_id].present?
    page = params[:page]
    page = 1 if page.blank? && !params[:page].present?
    @matches = @matches.paginate(:page => page, :per_page => 20)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  def details_matches_path
  end
  # GET /matches/:id/close
  def close 
      @match = Match.find(params[:match_id])
      @match.status = 2
      @match.goals_local_team = 0 if @match.goals_local_team.nil?
      @match.goals_visitant_team = 0 if @match.goals_visitant_team.nil?
      @match.save
      redirect_to '/matches?championship_id=' << @match.championship_id.to_s, notice: 'Match was successfully closed.'

  end


  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  def generate_form
     @championship_id=params[:championship_id]
     @championships=Championship.all
  end

  # GET /generate/1/matches
  def generate
     @championship =Championship.find(params[:championship_id])
     @teams = Team.where(championship_id: @championship.id)
     @count_matches=(@teams.count * (@teams.count - 1))/ 2
     cont = 0
     @teamsr= []
     @teams.each do | team | 
         @teamsr[cont]=team.id
         cont=cont + 1;
     end
     days_game = @championship.game_days.split(',') 
     if @teams.count.even?
        @count_matches_date = @teams.count / 2
        @count_date = @teams.count - 1
        cont=0
        @matchesr=Array.new(@count_date) { Array.new(@count_matches_date) }
        for x in (0..@count_date - 1) 
            for y in (0..@count_matches_date - 1)
                @matchesr[x][y]=@teamsr[cont]
                cont += 1
                if cont == @teamsr.count - 1
                  cont = 0
                end
            end
        end
        cont = @teamsr.count - 2
        for x in (0..@count_date - 1) 
            for y in (0..@count_matches_date - 1)
                 if y==0
                    @matchesr[x][y]=@matchesr[x][y].to_s << "-" << @teamsr.last.to_s
                 else
                    @matchesr[x][y]=@matchesr[x][y].to_s << "-" << @teamsr[cont].to_s
                    cont -= 1
                    if cont < 0
                      cont = @teamsr.count - 2
                    end
                 end
            end
        end
        write_matches(@matchesr,@championship.matches_simultanius,days_game,@championship.id)
     else
        @count_matches_date = (@teams.count - 1) / 2
        @count_date = @teams.count 
        cont=0
        @matchesr=Array.new(@count_date) { Array.new(@count_matches_date + 1) }
        for x in (0..@count_date - 1) 
            for y in (0..@count_matches_date)
                @matchesr[x][y]=@teamsr[cont]
                cont += 1
                if cont == @teamsr.count 
                  cont = 0
                end
            end
        end
        cont = @teamsr.count - 1 
        for x in (0..@count_date - 1) 
            for y in (0..@count_matches_date)
                 if y==0
                    @matchesr[x][y]=@matchesr[x][y].to_s << "-" << "libre"
                 else
                    @matchesr[x][y]=@matchesr[x][y].to_s << "-" << @teamsr[cont].to_s
                    cont -= 1
                    if cont < 0
                      cont = @teamsr.count - 1
                    end
                 end
            end
        end
        write_matches(@matchesr,@championship.matches_simultanius,days_game,@championship.id,true)
     end
     redirect_to '/matches?championship_id=' << @championship.id.to_s, notice: 'Programation was successfully created.'
  end


  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_matches 
      
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:local_id, :visitant_id, :match_date, :date_number, :championship_id, :date_start,:goals_local_team,:goals_visitant_team,:page,:match_id)
    end
    # function that calculates the next play date
    # Params:
    # - date_matche: Time -  it contains last date of game
    # - days_game: array of string - it contains number days of week of game
    def get_dates_matche  (date_matche,days_game)
      flag_continue=true
      while flag_continue do
        date_matche = date_matche + 1.days
        day_week=date_matche.wday
        if days_game.include?(day_week.to_s)
           return date_matche
        end 
      end
    end
    # function that writes the database programming games
    # Params:
    # - matches: array of string  - it  contains crossings teams
    # - flag_even: Boolean - flag used to see if it is of type pair
    # - simultaneous_games: Integer - is contains quantity of simultaneous games
    # - days_game: array of string - it contains number days of week of game (parameter necessary to calculate date matche)
    def write_matches (matches,simultaneous_games,days_game,championship_id,flag_uneven=false)
        counter_date_number=1;
        counter_simultaneous_games=1
        date_game_matche = Time.parse(params[:date_start])
        puts "fecha:" << date_game_matche.to_s
        matches.each do | row |
           row.each_with_index do | col, key |
             if key == 0  &&  flag_uneven
                next
             end
             matchr = col.split('-')
             local_id = matchr[0].to_i
             visit_id = matchr[1].to_i
             match= Match.create(local_id:local_id,visitant_id:visit_id,match_date:date_game_matche,date_number:counter_date_number,championship_id:championship_id)
             counter_simultaneous_games += 1
             if counter_simultaneous_games > simultaneous_games
                counter_simultaneous_games = 1
                date_game_matche=get_dates_matche(date_game_matche,days_game)
             end
           end
           counter_date_number += 1
        end
    end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :local,class:"mdl-textfield__label grey-text"
    = f.text_field :local_id,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :visitant,class:"mdl-textfield__label grey-text"
    = f.text_field :visitant_id,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :match_date,class:"mdl-textfield__label grey-text"
    = f.text_field :match_date,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :date_number,class:"mdl-textfield__label grey-text"
    = f.number_field :date_number,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :championship,class:"mdl-textfield__label grey-text"
    = f.text_field :championship_id,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :goals_local_team,class:"mdl-textfield__label grey-text"
    = f.text_field :goals_local_team,class:"mdl-textfield__input"
  .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    = f.label :goals_vistant_team,class:"mdl-textfield__label grey-text"
    = f.text_field :goals_visitant_team,class:"mdl-textfield__input"
  .actions
    = f.submit 'Save', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored"

app/views/matches/_form_generate.html.erb
  <%= form_tag({controller: "matches", action: "generate"}, method: "post" ) do |f| %>
    <div class="form-group row">
      <%= label_tag(:championship_id, "championship:",:class => "col-sm-2 col-xs-12 col-form-label") %><br>
      <div class="col-sm-3 col-xs-12">
        <% options = @championships.map { |city| [city.name, city.id] } %>
        <%= select_tag(:championship_id,options_for_select(options,@championship_id),:class=>"form-control",:prompt => 'Please select',:selected=>@championship_id) %>
      </div> 
    </div>
    <div class="form-group row">
      <%= label_tag(:date_start, "Date start:",:class => "col-sm-2 col-xs-12 col-form-label") %>
      <div class="col-sm-3 col-xs-12">
        <%= text_field_tag(:date_start,nil,:class => "form-control") %>
      </div>
    </div>
    <div class="form-group row">
         <div class="col-md-offset-2 col-sm-4">
           <%= submit_tag("Generate",:class=>"btn btn-success") %>
         </div>
    </div>
    <div class="form-group row">
         <div class="col-md-offset-2 col-sm-4">
           <a href="/championships" class="btn btn-secondary active"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back</a>
         </div>
    </div>
  <% end %>

app/views/matches/details_form.html.erb
<h1> Details matches</h1>
<div class="col-xs-8">
	  <%= form_tag({controller: "matches", action: "details"}, method: "post" ) do |f| %>
	      <div class="col-xs-4">
	          <fieldset class="form-group">
	            <%= hidden_field_tag('match_id', @match.id) %>
	            <%= label_tag(:team_id, "Team:") %><br>
			    <% players_local_array = [[@match.local.name, @match.local.id], [@match.visitant.name, @match.visitant.id]] %>
			    <%= select_tag(:team_id,options_for_select(players_local_array),:class=>"form-control",:prompt => '- choose -' ) %> 
			   <div class="form-group autocomplete-player">
			    <%= label_tag(:player_name, "Player:") %><br>
				   <div class="input-group">
				    <%= text_field_tag(:player_name,nil,:class => "form-control") %>
				     <span class="input-group-addon">
	                 	     <i class="glyphicon glyphicon-search"></i>
	                 </span>
				   </div>
			   </div>
	            <%= hidden_field_tag('player_id', 0) %>
			   
			   <div class="form-group">
			    <%= label_tag(:event_id, "Event:") %><br>
			    <% events_array = @events.map { |event| [event.name, event.id] } %>
			    <%= select_tag(:event_id,options_for_select(events_array),:class=>"form-control",:prompt => '- choose -' ) %>
			   </div>
			   <div class="form-group">
			    <%= label_tag(:minute, "Minute:") %>
			    <%= text_field_tag(:minute,nil,:class => "form-control") %>
			   </div>
			   <div class="form-group">
			     <%= submit_tag("Save event local",:class=>"btn btn-success center-element") %>
			   </div>
		      </fieldset>
	      </div>
	  <% end %>
</div>

app/views/matches/edit.html.haml
.col-xs-20.col-sm-10.col-md-8.col-lg-6 
  .box       
    .big-padding
      %h1 Editing matche

      = render 'form'
      = link_to 'Show', @matche
      = link_to 'Back', matches_path

app/views/matches/generate.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<p>Fecha inicio:<%=  @date_start %></P>
<p>Campeonato: <%= @championship.name %></P>
<p>Cantidad Equipos:<%=  @teamsr.count %></P>
<p>Cantidad partidos:<%=  @count_matches %></P>
<p>Cantidad jornadas:<%=  @count_date %></P>
<p>Partidos X jornada:<%=  @count_matches_date %></P>
<p>Partidos X jornada:<%=  @matches %></P>


<% @teams.each do |team| %>
        <p><%= team.id %>-<%= team.name %></P>
<% end %>

<table border=1>

<% @matchesr.each do |row| %>
       <tr>
      <% row.each do |colum| %>
        <td> <%= colum %></td>
      <% end %>
       </tr>
<% end %>
<table>

app/views/matches/generate_form.html.erb
<div class="col-xs-12 col-md-9 col-md-offset-3">
      <h2> Programation of matches</h2>
       <%= render 'form_generate' %>
</div>

app/views/matches/index.html.haml
.col-xs-12.col-sm-12.col-md-12.col-lg-12{"style"=>"background: white;"}
  .big-padding
    .big-padding{"style"=>"border:solid #f7f7f9;"}
      %h1 Matches
      %table.table.table-striped
        %thead
          %tr
            %th #
            %th Local
            %th Visitant
            %th Match date
            %th Date number
            %th Championship
            %th Result
            %th status
            %th Actions

        %tbody
          - @matches.each do |match|
            %tr
              %td= match.id
              %td= match.local.name
              %td= match.visitant.name
              %td= match.match_date
              %td= match.date_number
              %td= match.championship.name
              %td= "#{match.goals_local_team} - #{match.goals_visitant_team.to_s.blank? && !match.goals_local_team.to_s.blank? ? 0.to_s : match.goals_visitant_team.to_s}" 
              - case match.status
                - when 0 
                  %td= "Programmed"   
                - when 1 
                  %td= "In game"   
                - when 2 
                  %td= "Finalized"   
              %td= link_to 'Details', 'details_match/' << match.id.to_s << '/new'
      = will_paginate @matches,:renderer => WillPaginate::ActionView::BootstrapLinkRenderer
 

app/views/matches/new.html.haml
.col-xs-20.col-sm-10.col-md-8.col-lg-6 
  .box       
    .big-padding
      %h1 New match
      = render 'form'
      = link_to 'Back', matches_path

app/views/matches/show.html.haml
%p#notice= notice

%p
  %b Local:
  = @match.local.name
%p
  %b Visitant:
  = @match.visitant.name
%p
  %b Match date:
  = @match.match_date
%p
  %b Date number:
  = @match.date_number
%p
  %b Championship:
  = @match.championship.name

= link_to 'Edit', edit_match_path(@match)
\|
= link_to 'Back', matches_path